### ISSUE TITLE
The plug-in cannot read and write data normally

### ISSUE THREAD

**Issue by ahdg6** [Xanium1/GemsEconomy#1]
I'm using mariadb(a fork of mysql),and the plugin can not read/write the vaule into table

logs:
[WARN]: java.sql.SQLException: No value specified for parameter 4
[WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
[WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
[WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
[WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
[WARN]:        at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2211)
[WARN]:        at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2191)
[WARN]:        at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2121)
[WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1162)
[WARN]:        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[WARN]:        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[WARN]:        at me.xanium.gemseconomy.data.MySQLStorage.createAccount(MySQLStorage.java:324)
[WARN]:        at me.xanium.gemseconomy.listeners.EconomyListener.lambda$onLogin$0(EconomyListener.java:39)
[WARN]:        at me.xanium.gemseconomy.listeners.EconomyListener$$Lambda$947/00000000E45A5E80.run(Unknown Source)
[WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[WARN]:        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by PS1TD** [comment]
Hey, I have the exact same issue. I am also trying to write to MariaDB. The plugin is able to connect to the database and create tables, but whenever I try to create a currency it does not get saved to the database, or when a player logs in I get thrown the same error as above. Could you(@Xanium1) please have a look at what is possibly causing this issue? Thank You.

**Comment by q1an1x** [comment]
Same. I'm using MySQL and the plugin wouldn't write anything to the database. Went back to an older version(4.8.3) and it works fine.

**Comment by Xanium1** [comment]
It doesn't work in 4.9 but 4.8.3?
